### ISSUE TITLE
[Feature] Add labelling github action

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#1]

**Comment by jayesh-srivastava** [comment]
Hi. Is there anything that needs to be done for this issue? Can you please explain a bit further?

**Comment by kaiwalyakoparkar** [comment]
Hey @jayesh-srivastava We need to add github action which has custom labelling system to the project

**Comment by jayesh-srivastava** [comment]
Hey, @kaiwalyakoparkar I haven't worked on something like this but I would love to work to. Will be searching on the internet and will try to add it. Can you assign me the issue?

**Comment by kaiwalyakoparkar** [comment]
Oh! :facepalm: I just pulled the merge. But don't worry tomorrow I am going to add many issues which would interest you. So sorry for that. I actually had the branch ready for that. Seeing for collaborating with you over other issues :)

**Comment by jayesh-srivastava** [comment]
Hey no worries, will continue to contribute.
