### ISSUE TITLE
[Doc] Add Docasaurus or Docsify

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#10]
Need to add the following features
- Community information page
- Command listing page (separating in categories when commands grow)
- Community and contributing guidelines.

**Comment by AAB007209** [comment]
Hi @kaiwalyakoparkar Bro . I want to work on this issue , could you guide me ?

**Comment by kaiwalyakoparkar** [comment]
@AAB007209 Thanks for your interest. Go for it. I will assign it to you. If you need any help let me know :smiley: 
- Docsify reference [docs](https://docsify.js.org/#/), [video](https://youtu.be/I9gvygtus7Q)
- Docasaurus reference [docs](https://docusaurus.io/), [video](https://youtu.be/I-hYKNgaMmE)
- Example what we have to make like [this](https://www.beccalyria.com/discord-documentation/#/create-local)

If you find any other resources feel free to use it.
**Note: Only use Docsify or Docasaurus whichever you feel comfortable with**

**Comment by AAB007209** [comment]
Thank you Brother. Will be Starting working on this issue now.

**Comment by AAB007209** [comment]
Hi Brother, can you provide me with Community classroom logo png ?

**Comment by kaiwalyakoparkar** [comment]
yes sure.
![Community-Classroom-Icon-PNG](https://user-images.githubusercontent.com/53310847/126958316-63cde81d-49a3-4148-b8ac-6f8ce7244669.png)
![Community-Classroom-Icon-Square](https://user-images.githubusercontent.com/53310847/126958323-20087557-789b-4bda-8e7d-4c4d4ce624a8.png)
![Logo-Text-Square](https://user-images.githubusercontent.com/53310847/126958324-62bc5028-1b67-435b-8e56-741d3c26924e.jpg)

**Comment by AAB007209** [comment]
Brother, I am stuck little what should i do now ?

**Comment by kaiwalyakoparkar** [comment]
@AAB007209 Can you explain the problem?

**Comment by AAB007209** [comment]
Yes brother. I have made 3 windows. first one is about coverpage and welcome to community page. Second window is a about community discord commands then third one about community contirbuting guidelines.
The problem is in second window my page is static. It is not scrolling at all. 

![2021-07-27](https://user-images.githubusercontent.com/62844406/127159241-af1f4976-fb6c-4c08-9227-ec8b120c79c7.png)

**Comment by kaiwalyakoparkar** [comment]
okay I will point out possible solutions
- Check if there is any typo while configuring something
- Try changing browsers etc
- See if you enable the scrolling settings (if any)
Try these solutions and let me know if it gets solved or not else we will have to collab over it through `Live Share` extension of VS code

**Comment by AAB007209** [comment]
@kaiwalyakoparkar I searched on Stackoverflow and got the solution bro. Thank you

**Comment by AAB007209** [comment]
I had one more doubt, from becca lyria docs what all commands i should add from manual commands section ?

**Comment by AAB007209** [comment]
@kaiwalyakoparkar Bro ?

**Comment by kaiwalyakoparkar** [comment]
@AAB007209 Don't add anything like that. Just make a page of all user commands. And admin-only command. Sorry for the late reply though :slightly_smiling_face: I appreciate your patience

**Comment by krishguptadev** [comment]
imho we should first start making markdown docs in a docs folder then try to add the docsify functionality

**Comment by krishguptadev** [comment]
I could add the docs if you could guide on what all do I have to add?
