### ISSUE TITLE
[Bug]:  Add Chinese, Japanese and American to the allowed list

### ISSUE THREAD

**Issue by kkhitesh** [kaiwalyakoparkar/classroom-monitor-bot#105]
### Describe the bug

Add Chinese, Japanese and American to the allowed list

**Comment by kaiwalyakoparkar** [comment]
@kkhitesh Could you please raise a pr?

**Comment by kkhitesh** [comment]
Sure, but i can't find the allowed words config

**Comment by Panquesito7** [comment]
> Sure, but i can't find the allowed words config

Here's the file for that: https://github.com/kaiwalyakoparkar/classroom-monitor-bot/blob/main/config.json

**Comment by kkhitesh** [comment]
Thanks
