### ISSUE TITLE
[Feature] Warning for profane language

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#13]
As a community being inclusive is important and language plays a big role in keeping a community inclusive. Feature request to warn people for not using English or using profane or slangs in the chat.

**Comment by SriSatyaT** [comment]
I want to give it a shot.

**Comment by SriSatyaT** [comment]
Hey @kaiwalyakoparkar. I want to give it a shot to this issue.

**Comment by kaiwalyakoparkar** [comment]
@SriSatyaT Good to hear that. Go for it if you need any help let me know :)

**Comment by SriSatyaT** [comment]
@kaiwalyakoparkar Sure!

**Comment by SriSatyaT** [comment]
@kaiwalyakoparkar I have some doubts. Lets have a discussion?

**Comment by SriSatyaT** [comment]
@kaiwalyakoparkar Have an issue.
![general - Google Chrome 26-07-2021 10_51_20](https://user-images.githubusercontent.com/78905067/126937100-6a190274-82c1-45ea-8b80-9f4504769fd8.png)
bot is popping a message when I use restricted words as well.

**Comment by SriSatyaT** [comment]
Let's have a discussion?

**Comment by SriSatyaT** [comment]
@kaiwalyakoparkar Facing an issue here. 
![general - Google Chrome 26-07-2021 10_51_20](https://user-images.githubusercontent.com/78905067/126964806-bf734a75-cb34-4ba2-84be-c257e5fa833f.png)

**Comment by kaiwalyakoparkar** [comment]
@SriSatyaT okay, don't worry. I will help you with some resources and will look into the issue.

**Comment by ctnkaan** [comment]
hey @kaiwalyakoparkar I can try this when I have time

**Comment by kaiwalyakoparkar** [comment]
@ctnkaan go for it. I will assign it to you. Let me know if you need any help

**Comment by ctnkaan** [comment]
PR #79 fixes this issue
