### ISSUE TITLE
[Bug] edTech word list too small

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#14]
We are against scammy edTech startups. We want to avoid people talking about it in the community. The warning system is implemented but the library is very small. The task is to add more words to list so it becomes more flexible.

**Comment by ItsMeIshan** [comment]
hey, @kaiwalyakoparkar I have successfully set up the project and I would like to contribute and work on this issue. can you please clarify how we will be adding more words for eg: adding words in the array or any better approach for it?

**Comment by ItsMeIshan** [comment]
I found out the file ```restrictedWords.js``` for the words so do we have to add more words in that array?
@kaiwalyakoparkar

**Comment by jayesh-srivastava** [comment]
Hey @ItsMeIshan Can you tell me how to set up the project?

**Comment by ItsMeIshan** [comment]
> Hey @ItsMeIshan Can you tell me how to set up the project?

hey @jayesh-srivastava I have created a [discussion](https://github.com/kaiwalyakoparkar/classroom-monitor-bot/discussions/12) for setting up the project and its pretty easy lets hop in!!

**Comment by kaiwalyakoparkar** [comment]
@ItsMeIshan Thanks you so much helping other folks and willing to contribute. Do one thing add words as you think as of now. And create a PR. and as soon as I confirm the list proposed by you I will merge it. So I can give suggestions and you can edit on the go. If you want you can also create draft PR for the same.
Go for it. I will assign this issue to you :) If you need any help let me know.

**Comment by ItsMeIshan** [comment]
> @ItsMeIshan Thanks you so much helping other folks and willing to contribute. Do one thing add words as you think as of now. And create a PR. and as soon as I confirm the list proposed by you I will merge it. So I can give suggestions and you can edit on the go. If you want you can also create draft PR for the same.
> Go for it. I will assign this issue to you :) If you need any help let me know.

that's really awesome I am getting started now!!

**Comment by ItsMeIshan** [comment]
hey @kaiwalyakoparkar i have selected some words but as we start adding more words in array the linear search implemented will make our code slow so what i have thought that before using array we can use ```.sort()``` method and then i can implement binary search to get a Big oh complexity of ```log n ```. Do tell me your views on it!

**Comment by kaiwalyakoparkar** [comment]
If that works correctly. I don't have any problem you can go for it. Just check every possible scope

**Comment by ItsMeIshan** [comment]
hey, @kaiwalyakoparkar please check the list of the words and suggest if more is to be added.
