### ISSUE TITLE
[Doc] Add setup details

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#15]
Adding how to setup and contribute to the bot.

**Comment by Ciggzy1312** [comment]
I just ended up setting up the bot
So I can sort it out

**Comment by kaiwalyakoparkar** [comment]
@Ciggzy1312 That's awesome :boom:! So you can make a pr to add it to readme temporarily. As we are going to have a frontend for docs and all in the coming future. Go ahead I will assign this to you. If you need any help. Let me know :slightly_smiling_face:

**Comment by Ciggzy1312** [comment]
Sure
