### ISSUE TITLE
[Bug] Change prefix to " cm! "

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#16]
The current prefix to call bot is `cc!` which does not match with the initials of the bot. Task is to change the prefix to `cm!` so that it matches the initials of the bot.

**Comment by Ciggzy1312** [comment]
I can work on this also :)

**Comment by kaiwalyakoparkar** [comment]
@Ciggzy1312 I like your enthusiasm. But as you already have taken 1 issue I would recommend complete that first and then come to this. And we can also give this opportunity to some absolute beginners to get started with this project. Many issues are coming soon for us :slightly_smiling_face:

**Comment by Ciggzy1312** [comment]
Yeah sure

**Comment by Amrutha1101** [comment]
Can I work on this issue ?

**Comment by Amrutha1101** [comment]
Hey, I've changes it in help.js, hey.js, links.js and also in restricted words.js too

**Comment by kaiwalyakoparkar** [comment]
@Amrutha1101 Sure, Go ahead. I will assign this to you. If you need any help let me know :)

**Comment by Amrutha1101** [comment]
Basically, I'll have to change cc to cm in
-hey.js
-help.js
-links.js
-restrictedWords.js
-config.json right?

**Comment by kaiwalyakoparkar** [comment]
No actually just go to `config.json` and change there

**Comment by Amrutha1101** [comment]
Ok

**Comment by kaiwalyakoparkar** [comment]
As this issue is solve in pr no #21 I will close it. New related issue #24
