### ISSUE TITLE
[Bug] Change Discord server link in Greetings action

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#22]
This Greeting workflow was generated from different repo so has old Discord link which has to be replaced with `Community Classroom` Discord server. 
**Community Classroom Discord:** https://discord.gg/K9kxUXvfND

**Comment by vind3v17** [comment]
Hey @kaiwalyakoparkar Could you assign me this issue. I would like to work on it.

**Comment by kaiwalyakoparkar** [comment]
@vind3v17 Sure, Go for it. If you need any help let me know.

**Comment by vind3v17** [comment]
Yes Sure. Thankyou!
