### ISSUE TITLE
[Bug] Commands reply have old `cc` form

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#24]
Recently bot initial was changed from `cc` to `cm` (Ref. ). But the bot replies still have `cc` written in them. The task is to go through bot commands and change wherever `cc` is written with `cm`.
Eg: 
`Just cc!help away` to 
`Just cm!help away`

**Comment by Amrutha1101** [comment]
I can contribute to this too can you assign it

**Comment by kaiwalyakoparkar** [comment]
@Amrutha1101 I like your enthusiasm. Go for it. I will assign it to you :boom:
