### ISSUE TITLE
[Feature] Add description/status to the bot 

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#25]
Many bots have a `Listening to !help` kind of status which helps user to navigate and get familer with bot. Currently it is not present in Classroom monitor. Task is to set up status for bot.

**Comment by vind3v17** [comment]
Hey @kaiwalyakoparkar I would like to work on this.

**Comment by vind3v17** [comment]
Could you plz tell me if I should add the code for Activity/Status directly into index.js?

**Comment by kaiwalyakoparkar** [comment]
@vind3v17 You will have to add code basically. Refer [this](https://github.com/kaiwalyakoparkar/Lilliputian-Bot/blob/main/Commands/presence.js) you will have to create separate file in Commands **Not in index.js**
