### ISSUE TITLE
[Bug] Deleting user's messages

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#28]
## Current Scenario
When a person talks about an edTech startup then the bot warns him in public and private. 

## Required Scenario
When a person talks about an edTech startup then both warn him in public and private and also delete's him/her/their message.

**Comment by juuz0** [comment]
I would like to work on it :)

**Comment by kaiwalyakoparkar** [comment]
Sure, go for it. Just make sure you test the following thing and add screenshots of same in PR
- Bot sees the message (You don't have to do anything here tbh)
- Bot warns the user is private and public
- and then deletes the message
Please make sure the bot follows the same order of execution. If possible add a gif in your PR. I will assign it to you. Lemme know if you need any help :slightly_smiling_face:

**Comment by kaiwalyakoparkar** [comment]
Thanks for raising a PR and solving this issue :slightly_smiling_face:

**Comment by kaiwalyakoparkar** [comment]
Please mention issues in your PR from next time. It will close issue automatically :smile:

**Comment by juuz0** [comment]
> Please mention issues in your PR from next time. It will close issue automatically :smile: 

Sure thanks for letting me know! :D
