### ISSUE TITLE
[Bug] Broken Image link

### ISSUE THREAD

**Issue by vind3v17** [kaiwalyakoparkar/classroom-monitor-bot#29]
### Describe the bug
**A clear and concise description of what the bug is :**
In the Readme.md file, the image link for 8th step for Setting Up the bot in local Environment is broken.

## Screenshots

![Screenshot_20210726-090739_Chrome](https://user-images.githubusercontent.com/83384807/126930405-835e123e-885b-402a-a71d-d5e16aee4806.jpg)

**Comment by VDA-001** [comment]
Hey @kaiwalyakoparkar, I have fixed this issue and raised a pr and wanted to know if it's ok to work on simple issue's without getting assigned if nobody is working on it

**Comment by kaiwalyakoparkar** [comment]
@VDA-001 Thanks for your enthusiasm. It is always recommended to stop until you get an issue assigned. This helps maintainers keep track also creates fewer conflicts. Hope you understand what I am trying to put forward :slightly_smiling_face:

**Comment by VDA-001** [comment]
@kaiwalyakoparkar yep sorry for that, I was a bit confused but now its clear

**Comment by kaiwalyakoparkar** [comment]
@VDA-001 Awesome. No worries. I will assign it to you so it gets confirmed
