### ISSUE TITLE
[Doc] Update Readme with commit example

### ISSUE THREAD

**Issue by juuz0** [kaiwalyakoparkar/classroom-monitor-bot#33]
## Add conventional commit guidelines

The project uses conventional commits specifications, but that isn't very known among beginners. 
Adding an example commit message would help greatly.

**Check List (Check all the boxes which are applicable)**

- [ ] Information addition regarding the newest change through a PR
- [ ] Typo error.
- [x] New category addition.
- [ ] Refractoring sentences that make more sense.
- [ ] Fixing broken links.
- [ ] Refractors / reformating of the document.

**Comment by Amrutha1101** [comment]
hey @kaiwalyakoparkar  this should be added into readme right? can I work on this issue?

**Comment by kaiwalyakoparkar** [comment]
Hey @Amrutha1101 Why not, go for it :smile: . Remember to include proper steps to create commit like eg `feat :emoji: changes`. You could include
- How to decide in `feat`, `fix`, `doc`, `chor`, `style` and many more refer [this](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13#types)
- How to get `:emoji-unicode-id:`
- How to write good commit message
