### ISSUE TITLE
[Feature] Contributor banner at the footer of Readme

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#35]
We would like to have a contributor footer like [this](https://github.com/kaiwalyakoparkar/sense-hacker#team-members--contributors). The current one is just the maintainer name.

**Comment by indujaaaa** [comment]
Hey @kaiwalyakoparkar, I'd like to contribute to this issue!

**Comment by kaiwalyakoparkar** [comment]
Hey @indujaaaa, Thanks for your interest. Go for it. I will assign it to you. Lemme know if you face any difficulties.

**Comment by indujaaaa** [comment]
Does this look good? @kaiwalyakoparkar 

![Screenshot](https://user-images.githubusercontent.com/53386868/126992084-ace3be36-bbc5-4929-9097-ca78495f90a2.png)

**Comment by kaiwalyakoparkar** [comment]
Hey, @indujaaaa just a follow-up. Are you working on it? Or did you start working on it? The reason for the follow-up was someone just created PR #38 fixing this issue. If you started already don't worry I will discard that PR until yours comes in. Or if you are fine with that PR let me know. There are many issues you can still work on :smiley:

**Comment by indujaaaa** [comment]
@kaiwalyakoparkar I'd finished working on it back then, I was just awaiting your reply before I make the PR. I'll make the PR now!

**Comment by kaiwalyakoparkar** [comment]
@indujaaaa Ok! Thank you so much. I will do the needful! :+1:
