### ISSUE TITLE
[Bug] Typo in the pull request template 

### ISSUE THREAD

**Issue by VarunSAthreya** [kaiwalyakoparkar/classroom-monitor-bot#39]
### Describe the bug
**A clear and concise description of what the bug is:**

There is a typo in the pull request template. 
In the 5<sup>th</sup> checklist under the  `Check List (Check all the boxes which are applicable)`  part. It must be `plagiarized` instead of `plagarised`.

### To Reproduce
**Steps to reproduce the behavior:**
1. Go to [here.](https://github.com/kaiwalyakoparkar/classroom-monitor-bot/blob/main/.github/pull_request_template.md#check-list-check-all-the-boxes-which-are-applicable)
2. Check the 5<sup>th</sup> checklist.
4. See the typo

### Screenshots/ Video
**If applicable, add screenshots to help explain your problem.**

![Capture](https://user-images.githubusercontent.com/64711780/127061926-556b9f83-c249-4800-813c-47c63dbfd763.PNG)

**Comment by kaiwalyakoparkar** [comment]
Thanks for reporting. Let me know if you would like to work on this :smile:

**Comment by VarunSAthreya** [comment]
Yaa sure.
