### ISSUE TITLE
[Feature] Convert the Issue templates with newer format.

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#42]
The current issues template is in the `.md` file we need to convert them to the `.yml` file which provides newer features while raising issues.

**Comment by VDA-001** [comment]
Hey @kaiwalyakoparkar, I would like to try this issue!

**Comment by kaiwalyakoparkar** [comment]
@VDA-001 Sure go ahead. I will assign this to you. If you need any help let me know :smiley:

**Comment by VDA-001** [comment]
Hey @kaiwalyakoparkar, I am getting the following error while trying to commit....not sure what husky is

⧗   input: Converting .md files to .yaml
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)

**Comment by kaiwalyakoparkar** [comment]
@VDA-001 add commit message as `fix: :gear: Converted issue template from md to yml format`  This is Conventional commits. You can also read section in Readme file regarding this. If you add this commit message it will pass the tests

**Comment by VDA-001** [comment]
Ohh ok got it, thank you.
