### ISSUE TITLE
[Bug] The bot isn't recognizing edTech names due to different letter case.

### ISSUE THREAD

**Issue by utkarsh1311** [kaiwalyakoparkar/classroom-monitor-bot#46]
### Describe the bug
**The list for edTech startups in restrictedWords.js is small and the bot isn't picking up some words in conversation due to the letter case. The bot recognizes "code for cause" as an edTech name but doesn't recognize "Code for cause" due to different letter case.**

### To Reproduce
**Steps to reproduce the behavior:**
1. Go to 'restrictedWords.js'
2. Add more edTech names to the words array and some modifications for pre-existing edTech names.

### Expected behavior
**The bot will be able to recognize more edTech names irrespective of different letter case**

**Comment by kaiwalyakoparkar** [comment]
Can you add screenshots and all to describe the issue more clearly?

**Comment by utkarsh1311** [comment]
Sure.
As you can see in the screenshot provided below, use *cool dude* mentioned Code for Cause in his message. But the **classroom-monitor-bot** was not triggered due to *C* being in the upper-case in the **Code for Cause** word. 
This is the problem that I want to solve by adding different letter-case examples in the list of edTech startups in ```restrictedWords.js``` and also adding some additional edTech names.
![WhatsApp Image 2021-08-03 at 9 56 20 AM](https://user-images.githubusercontent.com/70108561/127957892-92e6734f-4679-4719-ad59-268f03c0b1cb.jpeg)

**Comment by kaiwalyakoparkar** [comment]
Alright, @utkarsh1311 I understood the error. The bot was not online at that time as I ran out of Heroku credits. If you try the same word now. You will get the same warning. :smiley: I am closing this issue as it was just bot availability problem :slightly_smiling_face:
