### ISSUE TITLE
[Feature] Detect when someone tags supreme mentor for no reason and issue a warning

### ISSUE THREAD

**Issue by bamblebam** [kaiwalyakoparkar/classroom-monitor-bot#48]
### Is your feature request related to a problem? Please describe.
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
A lot of people just tag kunal for asking the simplest of doubts, this can be really disturbing.

### Describe the solution you'd like
**A clear and concise description of what you want to happen.**
Just detect his name and issue a warning if someone does this. After multiple warnings something could be done.

### Describe alternatives you've considered
**A clear and concise description of any alternative solutions or features you've considered.**
We could have a centralized naughty list where we keep count of all infractions and could ban people if it increases a certain amount. But this should probably be a new issue in itself.

**Comment by kaiwalyakoparkar** [comment]
Hey, I appreciate your idea. But Kunal has clearly stated that's it's okay to tag him. So taking action for the same wouldn't be a good idea. Kunal has told me to not do so specifically. So I am really sorry, I won't be able to take this idea forward. Hence I am closing this. Hope you understand :slightly_smiling_face:
