### ISSUE TITLE
[Feature]Add the bootcamp roadmap repository link to the links command

### ISSUE THREAD

**Issue by Ciggzy1312** [kaiwalyakoparkar/classroom-monitor-bot#53]
### Is your feature request related to a problem? Please describe.
Most people are asking for the repository link which will be followed in the bootcamp

### Describe the solution you'd like
We can add the repository link to the links command section

**Comment by kaiwalyakoparkar** [comment]
Nice thought @Ciggzy1312 Would you like to work on this?

**Comment by Ciggzy1312** [comment]
Yes

**Comment by kaiwalyakoparkar** [comment]
Okay, Go ahead I have assigned this to you. If you face any issues let me know.
