### ISSUE TITLE
[Bug] Wrong command on README.md

### ISSUE THREAD

**Issue by VDA-001** [kaiwalyakoparkar/classroom-monitor-bot#54]
### Describe the bug

Wrong command to create new git branch on README.md

Output:
error: unknown switch `b'

### To Reproduce
**Steps to reproduce the behavior:**
Change 'git branch -b (your-branch-name)' to 'git checkout -b (your-branch-name)'

### Expected behavior
Create a new branch and move into it

### Screenshots/ Video

![CommandError](https://user-images.githubusercontent.com/67089703/127695410-5ca77773-9504-4525-bf19-460fe8a59c01.png)

**Comment by bamblebam** [comment]
Yeah this should be: git checkout -b ＜new-branch＞

**Comment by kaiwalyakoparkar** [comment]
Oh! Nice spot @VDA-001 would you or @bamblebam would like to work on this?

**Comment by VDA-001** [comment]
oh yeah sure!

**Comment by kaiwalyakoparkar** [comment]
Okay, @VDA-001 go ahead. I have assigned this to you

**Comment by bamblebam** [comment]
@VDA-001 are you having difficulties with this ?

**Comment by VDA-001** [comment]
@bamblebam Nope I have already submitted the pr for this issue

**Comment by VDA-001** [comment]
@kaiwalyakoparkar I have submitted the pr for this, Is there anything else to add
