### ISSUE TITLE
[Bug]: `cm!dsa` command not working

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#62]
### Describe the bug

The bot does not respond with an embed with typed `cm!dsa`

### To Reproduce

- Go to community classroom server
- Go to #bot-spam
- type `cm!dsa`

### Expected Behavior

It should return the embed present in `Commands/DSA.js` file

**Comment by VDA-001** [comment]
Hey @kaiwalyakoparkar, the command is working fine
![discord](https://user-images.githubusercontent.com/67089703/127855316-03cda2f2-2542-4559-92fc-7d8ab52ca84f.png)

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for informing @VDA-001 I guess when I opened this issue it was under release cycle so might have caused some delay. I will close this issue now
