### ISSUE TITLE
[Feature]: Hindi and English translation

### ISSUE THREAD

**Issue by ctnkaan** [kaiwalyakoparkar/classroom-monitor-bot#64]
### Is your feature request related to a problem? Please describe.

I'm thinking of adding a Hindi to English and English to Hindi translation feature if this feature is not already implemented.
I thought about this feature because the community is mainly made out of Indian students and even though everyone speaks English 95% of the time it might help non Hindi speakers 5% of the time. 

It might also help Indian students for translating English to Hindi for specific times.

### Describe the solution you'd like

I'm thinking of using a third party library called translate
https://www.npmjs.com/package/translate

**Comment by ctnkaan** [comment]
@kaiwalyakoparkar Feel free to assign me to this issue if you find it cool.

**Comment by kaiwalyakoparkar** [comment]
@ctnkaan really great thought. I have assigned it to you. If you need any help please do let me know.

**Comment by ctnkaan** [comment]
Closing this because of PR #65
