### ISSUE TITLE
[Feature]: Reddit Programmer Memes

### ISSUE THREAD

**Issue by ctnkaan** [kaiwalyakoparkar/classroom-monitor-bot#66]
### Is your feature request related to a problem? Please describe.

We have a memes channel in the Discord server. I think it would be fun to have a command so the bot can send memes from r/programmerhumor. Specially r/programmerhumor because some memes from other subreddits have a chance to be offensive.

### Describe the solution you'd like

I already have a working demo of a Discord Reddit Bot using meme.js

https://www.npmjs.com/package/memejs

### Describe alternatives you've considered

I did not think of any alternatives since I already have a demo.

### Here is the Demo

![image](https://user-images.githubusercontent.com/59853931/130246175-a7948e00-245a-42f9-a2cc-d4f8500ce450.png)

**Comment by ctnkaan** [comment]
@kaiwalyakoparkar feel free to assign me to this if you want it to be implemented 👍

**Comment by kaiwalyakoparkar** [comment]
@ctnkaan this sounds fun. Go ahead with it. I will assign this to you :)

**Comment by ctnkaan** [comment]
Closing this because of PR #68
