### ISSUE TITLE
[Feature]: Add Cucumber tests

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#69]
### Is your feature request related to a problem? Please describe.

There are no tests to check the authenticity and integration of the pull requests

### Describe the solution you'd like

Writing cucumber tests to ensure the ci and cd

**Comment by kaiwalyakoparkar** [comment]
@vishalda Thank you so much for your interest. Go ahead with it. You can follow yt tutorials. If I find any specific I will share it here :slightly_smiling_face:

**Comment by vishalda** [comment]
Hey @kaiwalyakoparkar quick clarification,
Should it be like, the GitHub actions run the test for every PR checking if every command of bot works?
(New to writing tests)

**Comment by kaiwalyakoparkar** [comment]
@vishalda Yes

**Comment by krishguptadev** [comment]
ig we can't create tests for discord bots?

**Comment by kaiwalyakoparkar** [comment]
@krishguptadev yes you are correct, I figured that out but forgot to close the issue
