### ISSUE TITLE
[Doc] Enhance Readme documentation

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/classroom-monitor-bot#7]
Add the following to the readme
- Logo of community
- Greeting
- Contributor guideline
- commands available
- purpose
- socials
- contributors list

**Comment by jayesh-srivastava** [comment]
Hey @kaiwalyakoparkar I would like to work on this. Just wanted to clarify all the contents which need to be added. Also can I assign the issue to myself.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava Thanks for your interest. I will assign this to you, You can refer to my other bot projects and points mentioned below to create a good readme. If you need any help let me know

**Comment by jayesh-srivastava** [comment]
Sure @kaiwalyakoparkar, just if you can a link of your previous bot's repo, that would be great.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava Sure, here you go [Repo Link](https://github.com/kaiwalyakoparkar/Lilliputian-Bot/)

**Comment by jayesh-srivastava** [comment]
Thanks @kaiwalyakoparkar, gotta start working on the README.

**Comment by jayesh-srivastava** [comment]
Also, just wanted to ask, can I not all add the features at once? Like some features after some. Will you approve the PR?

**Comment by kaiwalyakoparkar** [comment]
I would encourage separate pr for every feature that would help me in reviewing and moving it to production.

**Comment by jayesh-srivastava** [comment]
That's great. Exactly what I wanted. Thanks.

**Comment by jayesh-srivastava** [comment]
Hey @kaiwalyakoparkar , added the first feature and made the PR. Needs your approval.

**Comment by jayesh-srivastava** [comment]
Hey @kaiwalyakoparkar can you please share what is to written under contributor guidelines and commands available?

**Comment by jayesh-srivastava** [comment]
Also now that I have made the original PR as the draft, after adding new features, I will have to edit that PR comment only and not will be able to send a new PR. Is that okay?

**Comment by kaiwalyakoparkar** [comment]
Okay, current commands can be found if you do `cc!help` and do one thing. Open a separate issues for separate features and make PR's to solve them 1 by 1. That would be a more systematic approach.

**Comment by jayesh-srivastava** [comment]
Yeah, that would be great. Thanks @kaiwalyakoparkar

**Comment by jayesh-srivastava** [comment]
Should I only make separate PRs or open new issues and make the PRs?

**Comment by kaiwalyakoparkar** [comment]
what more changes do you have in mind?

**Comment by jayesh-srivastava** [comment]
I have some. Like what you mentioned in the issue, those and some other like about section. I'll do one thing, I'll open up separate issues and make the PRs for them. Sounds good?

**Comment by kaiwalyakoparkar** [comment]
Okay let me clear a thing. I guess I confused it.
In your current PR you should submit complete readme.
- Icons
- welcome
- about
- setting up project
- contributing guidelines
- Thanking contributor
Other things can be added by opening new Issue and PR

**Comment by kaiwalyakoparkar** [comment]
Okay let me clear a thing. I guess I confused it.
In your current PR you should submit complete readme.
- Icons
- welcome
- about
- setting up project
- contributing guidelines
- Thanking contributor
Other things can be added by opening new Issue and PR

**Comment by jayesh-srivastava** [comment]
Okay got it. No worries, anytime you feel like clearing up anything, just text. I am always available.

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava no problem. Hope it's a bit more clear now. We need a basic doc (with the above sections) to release the first stable version.

**Comment by jayesh-srivastava** [comment]
@kaiwalyakoparkar Yeah.

**Comment by jayesh-srivastava** [comment]
One thing I forgot to ask, what to write in contributors guidelines. @kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@jayesh-srivastava Redirect them to contributing.md with a nice message. (Add a link of it basically)

**Comment by jayesh-srivastava** [comment]
Sure got it.
