### ISSUE TITLE
Bot also replies in dm

### ISSUE THREAD

**Issue by Tan-Shadow** [kaiwalyakoparkar/classroom-monitor-bot#73]
### Describe the bug

the bot will reply on the command even if its dm

### To Reproduce

Dm the bot `cm!help`
It will reply

### Screenshot/ Video

https://tanshadow.is-inside.me/JNGa5Jqn.png

**Comment by kaiwalyakoparkar** [comment]
I guess commands work in DM :thinking:

**Comment by Tan-Shadow** [comment]
my second issue has the solution for this one

**Comment by krishguptadev** [comment]
Commands should not work in dms imo

**Comment by kaiwalyakoparkar** [comment]
> Commands should not work in dms imo

Nope, that's okay. It becomes handy sometimes

**Comment by krishguptadev** [comment]
> > Commands should not work in dms imo
> 
> Nope, that's okay. It becomes handy sometimes

What would you do after discord sets it to be as-if no messages can be read... They have that on their roadmap... Also replying in dms requires special setup after v13 this means they want us to avoid the use of dms in bots

**Comment by kaiwalyakoparkar** [comment]
> What would you do after discord sets it to be as-if no messages can be read... They have that on their roadmap... Also replying in dms requires special setup after v13 this means they want us to avoid the use of dms in bots

Oh, I was not aware of this. :thinking: Then this makes sense. Please make a relative or for fixing this
