### ISSUE TITLE
[Feature]: Add warnings for when non inclusive words are used. 

### ISSUE THREAD

**Issue by SiddhantKhisty** [kaiwalyakoparkar/classroom-monitor-bot#77]
### Describe the solution you'd like

Currently we are using just carl bot to ask people only to refrain from using the word 'guys'. The classroom monitor can be configured to display a message saying something like "This word is not promoting inclusivity. Please use a inclusive word"
Possible words to warn for are as follows:
    'guyz',
    'guys',
    'guyzz',
    'bruh',
    'duude',
    'women',
    'sir',
    'sirr',
    'man',
    'fellas',
    'madam',
    'maam',
    "ma'am",
    'yessir',
    'chad',
    'simp',
    'mate',

**Comment by SiddhantKhisty** [comment]
Tried to implement this feature and opened a PR. Not sure if it works as i do not know how to test the bot. Please take a look at it when you have the time

**Comment by ctnkaan** [comment]
Sorry tagged the wrong issue at my PR
