### ISSUE TITLE
[Bug]: Small typo in README file

### ISSUE THREAD

**Issue by shuklaritvik06** [kaiwalyakoparkar/classroom-monitor-bot#80]
### Describe the bug

Small typo in the README file

### Expected Behavior

It should be Local

### Screenshot/ Video

![imageedit_1_9030410858](https://user-images.githubusercontent.com/72812470/134245659-b1efd20c-ea51-4960-8c41-c2a5dc07af05.png)

**Comment by kaiwalyakoparkar** [comment]
Hey @shuklaritvik06 would you like to go ahead with this issue?

**Comment by shuklaritvik06** [comment]
> Hey @shuklaritvik06 would you like to go ahead with this issue?

Created a PR :)
