### ISSUE TITLE
[Feature]: Add Scam Detection

### ISSUE THREAD

**Issue by ctnkaan** [kaiwalyakoparkar/classroom-monitor-bot#83]
### Is your feature request related to a problem? Please describe.

Scam malwares are increasing in Discord. These scam malwares basically transform users to bots. These infected users are then made to send infectious links to multiply them selves to all channels with @everyone tag.

### Describe the solution you'd like

These scam links are always the same. I have been gathering some data about their patters. A simple if code to detect if the link has been sent can detect and remove the messege.

### Describe alternatives you've considered

Did not think of any other alternative solutions.

**Comment by ctnkaan** [comment]
@kaiwalyakoparkar feel free to assign this to me if you want it to be implemented 👍

**Comment by kaiwalyakoparkar** [comment]
Thank you so much for the interest @ctnkaan. I have assigned it to you now
