### ISSUE TITLE
[Bug]: Profane warning for 'Class'

### ISSUE THREAD

**Issue by SiddhantKhisty** [kaiwalyakoparkar/classroom-monitor-bot#84]
### Describe the bug

The bot sends a profance word warrning for the word 'Class'. 

### To Reproduce

Type 'Class' with Community Monitor in your server.

**Comment by krishguptadev** [comment]
How can I fix this issue?

**Comment by SiddhantKhisty** [comment]
Issue Update: I think the error is with any word using with 'ss' eg: class, glass.

**Comment by SiddhantKhisty** [comment]
@krishguptadev I think the issue is in the restrictedwords.js. Maybe some files need to be updated there but I cannot see any code lines there which might be causing the issue

**Comment by SiddhantKhisty** [comment]
I think the issue is being caused due to the word 'ass'. since the words 'class' and 'glass' have a substring of 'ass' It is throwing a warning when those workds are invoked. I think in order to solve this issue an excpetion file may have to be made that excludes 'ass' if it is a substring

**Comment by krishguptadev** [comment]
How about using alexjs for the purpose? Just like EddieHubCommunity/EddieBot does that

**Comment by SiddhantKhisty** [comment]
I dont know about alexjs, could you implement it please?

**Comment by krishguptadev** [comment]
I am talking about this: https://alexjs.com/ Can I get assigned to implement alexjs instead of the old method?

**Comment by SiddhantKhisty** [comment]
I'd really appreciate it if you could implement alexjs. I do not have the assignment permission but I will ask the maintainer to assign you this issue :)
