### ISSUE TITLE
[Bug]: Profane Warning on wrong words

### ISSUE THREAD

**Issue by SiddhantKhisty** [kaiwalyakoparkar/classroom-monitor-bot#99]
### Describe the bug

The bot is throwing profane warnings for words which are not profane. 
In order to solve this error:
1. Monitor the discord chat and make a list of words which are non profane but a warning is being thrown.
2. Add the words which you have found to the `allow` list in `Config.json`

Words that have been found up till now:
simple
simply
fellowship
guys 
ball
Obviously
white
black
crashes
crash
Host

**Comment by kaiwalyakoparkar** [comment]
@SiddhantKhisty Could you please add a word list?

**Comment by SiddhantKhisty** [comment]
@kaiwalyakoparkar I'll add the words as I find them and complie the list

**Comment by kaiwalyakoparkar** [comment]
@SiddhantKhisty Okay, please add it in the description of this issue
